#ifndef SRAM_H_
#define SRAM_H_

#include "screen.h"


// SRAM
#define SRAM              ((void *)0xd0000000)
#define SRAM_ADDR         (0xd0000000)
#define SRAM_SIZE         524288

#define STR2IMG_INTERNAL_BUFFER 				SRAM
#define STR2IMG_INTERNAL_BUFFER_ADDR 			SRAM_ADDR
#define STR2IMG_INTERNAL_BUFFER_SIZE			9600

#define SCREEN_INFO 							(STR2IMG_INTERNAL_BUFFER + STR2IMG_INTERNAL_BUFFER_SIZE)
#define SCREEN_INFO_ADDR						(STR2IMG_INTERNAL_BUFFER_ADDR + STR2IMG_INTERNAL_BUFFER_SIZE)
#define SCREEN_INFO_SIZE						((SCREEN_MAX_ITEMS+4) * SCREEN_MAX_WIDTH)

#define FRAME_BUFFER							(SCREEN_INFO + SCREEN_INFO_SIZE)
#define FRAME_BUFFER_ADDR						(SCREEN_INFO_ADDR + SCREEN_INFO_SIZE)
#define FRAME_BUFFER_SIZE						76800

#define FRAME_BUFFER_2							(FRAME_BUFFER + FRAME_BUFFER_SIZE)
#define FRAME_BUFFER_2_ADDR						(FRAME_BUFFER_ADDR + FRAME_BUFFER_SIZE)
#define FRAME_BUFFER_2_SIZE						76800

#define SCRIPT_LOAD								(FRAME_BUFFER_2 + FRAME_BUFFER_2_SIZE)
#define SCRIPT_LOAD_ADDR						(FRAME_BUFFER_2_ADDR + FRAME_BUFFER_2_SIZE)
#define SCRIPT_LOAD_SIZE						1024

#define DATA_FILE_PARSE							(SCRIPT_LOAD + SCRIPT_LOAD_SIZE)
#define DATA_FILE_PARSE_ADDR					(SCRIPT_LOAD_ADDR + SCRIPT_LOAD_SIZE)
#define DATA_FILE_PARSE_SIZE					512

#define FRAME_OSD								(DATA_FILE_PARSE + DATA_FILE_PARSE_SIZE)
#define FRAME_OSD_ADDR							(DATA_FILE_PARSE_ADDR + DATA_FILE_PARSE_SIZE)
#define FRAME_OSD_SIZE							128

#endif
